config/routes.rb
Rails.application.routes.draw do 
resources :categories do
  member do
    get :edit_questions
    patch :update_questions
  end
end

namespace :public do
  resources :categories, only: [:index, :show] do
    member do
      get :answer
      post :submit_answers 
      get  :show_category_answers 
    end
  end
end
 devise_for :admin, controllers: {
  sessions: 'admin/sessions'
}, skip: [:registrations]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root "pages#home"
  get "pages/users"
  get "pages/admin"



resources :user_answers, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
   has_many :categories
   has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :admin
  has_many :questions,dependent: :destroy
  accepts_nested_attributes_for :questions,allow_destroy: true
  has_one_attached :category_picurl
  validates :category_name, :category_picurl, presence:true
  
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :category
  belongs_to :admin 
  has_many :user_answers, dependent: :destroy
  has_one_attached :question_picurl
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!,
  def new
    @category = Category.new
  end

  def create
    @category = current_admin.categories.build(category_params)
    @category.questions.each do |question|
      question.admin_id=current_admin.id
    end
    if @category.save
      redirect_to pages_admin_path, notice: "Category created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit_questions
  @category = Category.find(params[:id])
  @category.questions.build if @category.questions.empty?
end

def update_questions
  @category = Category.find(params[:id])

  # Assign incoming attributes WITHOUT saving yet
  @category.assign_attributes(category_params)

  # Assign current_admin.id to all questions missing admin_id (new questions)
  @category.questions.each do |question|
    question.admin_id ||= current_admin.id
  end

  if @category.save
    redirect_to  pages_admin_path, notice: "Questions updated successfully."
  else
    render :edit_questions, status: :unprocessable_entity
  end
end


def destroy
  @category = Category.find(params[:id])
  if @category.destroy
    flash[:notice] = "Quiz deleted successfully."
  else
    flash[:alert] = "Failed to delete quiz."
  end
  redirect_to pages_admin_path
end


  private
  def category_params
    params.require(:category).permit(
      :category_name,
      :category_description,
      :category_picurl,
      questions_attributes: [:content, :question_picurl,:answer1,:id, :answer2, :answer3, :answer4, :correct_answer , :_destroy]
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action:authenticate_user!,only:[:users ]
   before_action:authenticate_admin!,only:[:admin,:newquiz]
  def home
  end

  def users
     @categories=Category.all
  end

  def admin
    @categories=Category.all
  end
  
  def newquiz
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/Navbar/_navbar.html.erb
<header class="h-16 border-b border-gray-300 max-w-6xl mx-auto backdrop-blur-xl flex items-center justify-between px-4 lg:px-0 sticky top-0 z-30">
  <!-- Logo -->
  <div class="bg-gradient-to-r from-rose-400 to-blue-400 bg-clip-text">
    <a href="/">
      <h1 class="text-transparent text-2xl font-semibold italic">Quizzz</h1>
    </a>
  </div>

  <% if user_signed_in? %>
    <div class="flex items-center gap-4">
      <%= link_to "Get Started", pages_users_path, class: "bg-gradient-to-br from-rose-400 to-blue-400 h-10 rounded-full px-4 w-fit flex items-center justify-center text-white font-semibold text-base hover:opacity-90 cursor-pointer" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "border border-rose-400 text-black h-10 bg-white rounded-full w-24 flex items-center justify-center font-semibold text-base hover:opacity-90 cursor-pointer hover:bg-blue-50 ease-in duration-200 transition-colors" %>
    </div>

  <% elsif admin_signed_in? %>
    <div class="flex items-center gap-4">
      <%= link_to "Dashboard", pages_admin_path, class: "bg-gradient-to-br from-rose-400 to-blue-400 h-10 rounded-full px-4 w-fit flex items-center justify-center text-white font-semibold text-base hover:opacity-90 cursor-pointer" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "border border-rose-400 text-black h-10 rounded-full w-24 flex items-center bg-white justify-center font-semibold text-base hover:opacity-90 cursor-pointer hover:bg-blue-50 ease-in duration-200 transition-colors" %>
    </div>

  <% else %>
    <div class="flex items-center gap-4">
      <%= link_to "Sign in", new_user_session_path, class: "bg-gradient-to-br from-rose-400 to-blue-400 h-10 rounded-full w-24 flex items-center justify-center text-white font-semibold text-base hover:opacity-90 cursor-pointer" %>
      <%= link_to "Sign up", new_user_registration_path, class: "border border-rose-400 bg-white text-black h-10 rounded-full w-24 flex items-center justify-center font-semibold text-base hover:opacity-90 cursor-pointer hover:bg-blue-50 ease-in duration-200 transition-colors" %>
    </div>
  <% end %>
</header>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Quizzz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet"  />

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body>
    <%= render "Navbar/navbar" %>
    <div class="max-w-6xl mx-auto px-4 xl:px-0  min-h-[calc(100dvh-64px)]">
        <% if flash[:alert].present? %>
        <div id="flash-message" class="px-6 py-3 mb-4 mx-auto text-center mt-2 rounded-xl md:w-[50%] w-[80%] bg-red-100 text-red-800">
            <%= flash[:alert] %>
        </div>
        <% end %>
          <% if flash[:success].present? %>
        <div id="flash-message" class="px-6 py-3 mb-4 rounded-xl mx-auto text-center mt-2  md:w-[50%] w-[80%] bg-green-100 text-green-800">
            <%= flash[:success] %>
        </div>
        <% end %>

        <%= yield %>
    </div>

<script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
</body>


</html>

app/views/pages/admin.html.erb
<div class="flex flex-col gap-2 w-full pb-4">
    <div class="flex justify-center w-full">
        <%= link_to new_category_path, class: "mt-4 border border-rose-400 text-black h-10 rounded-full w-fit px-4 shadow-xl flex items-center justify-center gap-2 font-semibold text-base hover:opacity-90 cursor-pointer hover:bg-blue-50 ease-in duration-200 transition-colors" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
        </svg>
        Add new quiz
        <% end %>
    </div>
    <div class="flex items-center gap-1 font-medium text-base">
        <h1>Total Quizes:</h1>
        <%= @categories.count %>
    </div>
    <div class="grid mt-2 lg:grid-cols-3 gap-4 grid-cols-1 sm:grid-cols-2">
        <% @categories.each do |cat| %>

        <div class="flex group flex-col relative gap-2 px-2 pt-4 pb-6 border border-gray-400 rounded-xl shadow-md">
            <% if cat.category_picurl.attached? %>
            <div class="aspect-[16/9] overflow-hidden rounded-xl">
                <%= image_tag url_for(cat.category_picurl), class:"rounded-xl aspect-[16/9] object-cover group-hover:scale-110 transition-all ease-in duration-200" %>
            </div>
            <% end %>

            <h1 class="font-semibold capitalize text-2xl"><%= cat.category_name %></h1>
            <h1 class="font-semibold capitalize text-gray-500 text-xs -mt-2"><%= cat.category_description %></h1>
            <div class="flex items-center gap-1 font-medium text-sm">
                <h1>Total Questions:</h1>
                <%= cat.questions.count %>
            </div>
            <%= link_to "Edit Questions", edit_questions_category_path(cat), class: "absolute right-2 text-sm bottom-6 text-blue-500 underline" %>
            <% modal_id = "delete-modal-#{cat.id}" %>

            <div data-controller="modal">

                <!-- Delete Button -->
                <button data-modal-target="<%= modal_id %>" data-modal-toggle="<%= modal_id %>" class="absolute right-2 text-sm bottom-1 text-red-500 underline cursor-pointer" type="button">
                    Delete Quiz
                </button>

                <!-- Delete Modal -->
                <div id="<%= modal_id %>" class="hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full overflow-y-auto overflow-x-hidden">
                    <div class="relative p-4 w-full max-w-lg mx-auto max-h-full">
                        <div class="bg-white rounded-xl p-4 shadow">
                            <div class="flex flex-col gap-4">
                                <h1 class="font-medium text-lg">Are you sure you want to delete your quiz?</h1>
                                <div class="flex justify-end">
                                    <%= form_with url: category_path(cat),
                                    data: {action: "submit->modal#hideModal"},
                                    method: :delete, data: { turbo: false }, class: "inline" do %>
                                    <%= submit_tag "Delete Quiz", 
                                       data: { confirm: "Are you sure?" }, 
                                      class: "text-white bg-red-400 hover:bg-red-500 rounded-xl w-fit px-4 py-1.5 cursor-pointer" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>



        </div>



        <% end %>
    </div>

</div>
</div>

app/views/pages/home.html.erb
<div class="relative min-h-[calc(100dvh-64px)] flex justify-center items-center overflow-hidden">
  <!-- Bottom Gradient Overlay -->
  <div class="fixed top-0 left-0 w-full  h-full bg-gradient-to-r from-rose-50 via-gray-50 to-blue-50 pointer-events-none z-0"></div>

  <!-- Main Content -->
  <div class="relative z-10 flex flex-col md:max-w-3xl lg:max-w-2xl mx-auto">
    <div class="bg-gradient-to-r from-blue-400 to-purple-600 bg-clip-text">
      <h1 class="lg:text-5xl text-4xl xl:text-6xl font-bold text-center text-transparent">
        Test Your Knowledge. Level Up Your Mind.
      </h1>
    </div>

    <p class="mt-4 text-sm md:text-base text-center text-gray-800 italic">
      Discover fun, interactive quizzes across music, movies, tech, and more. Challenge yourself — or compete with friends.
    </p>

    <div class="flex justify-center mt-8">
      <%= link_to "Get Started", pages_users_path, class: "bg-gradient-to-br from-blue-400 to-purple-400 h-10 md:h-11 rounded-full px-8 w-fit flex items-center justify-center text-white font-semibold text-base md:text-lg hover:opacity-90 cursor-pointer" %>
    </div>
  </div>
</div>

app/views/pages/newquiz.html.erb
<%=link_to ("Add new quiz")  %>

app/views/pages/users.html.erb
<div class="flex flex-col gap-2 w-full">
    <div class="flex items-center gap-1 font-medium text-base mt-4">
        <h1>Total Quizes:</h1>
        <%= @categories.count %>
    </div>
    <div class="grid mt-2 lg:grid-cols-3 gap-4 grid-cols-1 sm:grid-cols-2">
        <% @categories.each do |cat| %>

        <div class="flex group flex-col relative gap-2 p-2 border border-gray-400 rounded-xl shadow-md">
            <% if cat.category_picurl.attached? %>
            <div class="aspect-[16/9] overflow-hidden rounded-xl">
                <%= image_tag url_for(cat.category_picurl), class:"rounded-xl aspect-[16/9] object-cover group-hover:scale-110 transition-all ease-in duration-200" %>
            </div>
            <% end %>

            <h1 class="font-semibold capitalize text-2xl"><%= cat.category_name %></h1>
            <h1 class="font-semibold capitalize text-gray-500 text-xs -mt-2"><%= cat.category_description %></h1>
            <div class="flex items-center gap-1 font-medium text-sm">
                <h1>Total Questions:</h1>
                <%= cat.questions.count %>
            </div>
            <div class="flex justify-end">
                <%= link_to "Join",   answer_public_category_path(cat), class: "bg-gradient-to-br from-blue-400 to-purple-400 h-8 rounded-full px-8 w-fit flex items-center justify-center text-white font-semibold text-sm hover:opacity-90  cursor-pointer" %>
            </div>
        </div>

        <% end %>
    </div>

</div>
</div>