config/routes.rb
Rails.application.routes.draw do 
resources :categories do
  member do
    get :edit_questions
    patch :update_questions
  end
end

namespace :public do
  resources :categories, only: [:index, :show] do
    member do
      get :answer
      post :submit_answers 
      get  :show_category_answers 
    end
  end
end
 devise_for :admin, controllers: {
  sessions: 'admin/sessions'
}, skip: [:registrations]
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  root "pages#home"
  get "pages/users"
  get "pages/admin"



resources :user_answers, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :admin
  has_many :questions,dependent: :destroy
  accepts_nested_attributes_for :questions,allow_destroy: true
  has_one_attached :category_picurl
  validates :category_name, :category_picurl, presence:true
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!,
  def new
    @category = Category.new
  end

  def create
    @category = current_admin.categories.build(category_params)
    @category.questions.each do |question|
      question.admin_id=current_admin.id
    end
    if @category.save
      redirect_to pages_admin_path, notice: "Category created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit_questions
  @category = Category.find(params[:id])
  @category.questions.build if @category.questions.empty?
end

def update_questions
  @category = Category.find(params[:id])

  # Assign incoming attributes WITHOUT saving yet
  @category.assign_attributes(category_params)

  # Assign current_admin.id to all questions missing admin_id (new questions)
  @category.questions.each do |question|
    question.admin_id ||= current_admin.id
  end

  if @category.save
    redirect_to  pages_admin_path, notice: "Questions updated successfully."
  else
    render :edit_questions, status: :unprocessable_entity
  end
end


def destroy
  @category = Category.find(params[:id])
  if @category.destroy
    flash[:notice] = "Quiz deleted successfully."
  else
    flash[:alert] = "Failed to delete quiz."
  end
  redirect_to pages_admin_path
end


  private
  def category_params
    params.require(:category).permit(
      :category_name,
      :category_description,
      :category_picurl,
      questions_attributes: [:content, :question_picurl,:answer1,:id, :answer2, :answer3, :answer4, :correct_answer , :_destroy]
    )
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<div class="border border-gray-400 rounded-xl p-4 mt-4 mb-4 md:max-w-3xl mx-auto">
    <%= form_with model: @category, local: true do |f| %>
    <h1 class="text-center text-2xl font-semibold"> Add Quiz? </h1>
    <div class="flex flex-col gap-2">
        <div>
            <%= f.label :category_name,class:"text-sm font-medium" %>
            <%= f.text_field :category_name, class: "w-full px-2 h-10 border focus:border text-sm focus:border-blue-400 border-gray-400 rounded-xl" %>
            <% if @category.errors[:category_name].any? %>
            <h1 class="text-sm text-red-600"><%= @category.errors[:category_name].first %></h1>
            <% end %>
        </div>

        <div>
            <%= f.label :category_description,class:"text-sm font-medium" %>
            <%= f.text_area :category_description, class: "w-full px-2 h-10 border min-h-[5rem] focus:border text-sm focus:border-blue-400 border-gray-400 rounded-xl" %>
        </div>

        <div>
            <%= f.label :category_picture,class:"text-sm font-medium" %>
            <%= f.file_field :category_picurl, class: "mt-1 block w-fit cursor-pointer text-sm  text-gray-900 file:bg-white file:ml-0 file:py-2 file:px-4 file:rounded-xl  file:text-sm file:font-semibold file:border file:border-rose-400 file:text-black hover:file:bg-blue-50" %>
            <% if @category.errors[:category_picurl].any? %>
            <h1 class="text-sm text-red-600"><%= @category.errors[:category_picurl].first %></h1>
            <% end %>
        </div>
    </div>
    <div id="questions" class="flex flex-col gap-4 pt-2">
        <%= f.fields_for :questions do |qf| %>
        <%= render 'question_fields', f: qf,index: qf.index.to_i + 1 %>
        <% end %>
    </div>
    <div class="flex items-center gap-4 mt-4">
        <%= link_to_add_association 'Add Question', f, :questions,
    class: " add-question inline-block text-white bg-blue-500 px-4 py-2 rounded hover:bg-blue-600 transition rounded-xl", data: { association_insertion_node: '#questions', association_insertion_method: :append } %>

        <%= f.submit "Create Quiz",class:"flex justify-end h-10 w-fit px-4 rounded-xl bg-green-400 flex items-center justify-center text-white" %>
    </div>

    <% end %>
</div>

app/views/categories/_question_fields.html.erb
<div class="nested-fields border border-gray-400 rounded-xl p-4">
    <%= f.hidden_field :id %>

    <div class="flex justify-center font-medium">
        Question
    </div>

    <div class="flex flex-col gap-2">
        <p>
            <%= f.label :content, class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.text_area :content, class: "w-full px-2 h-10 min-h-[5rem] border focus:border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <div data-controller="image-preview">
            <%= f.label :question_picurl, "Question Picture", class: "text-sm font-medium" %><br>

            <%= f.file_field :question_picurl,
      class: "mt-1 block w-fit cursor-pointer text-sm text-gray-900 file:bg-white file:ml-0 file:py-2 file:px-4 file:rounded-xl file:text-sm file:font-semibold file:border file:border-rose-400 file:text-black hover:file:bg-blue-50",
      accept: "image/*",
      data: {
        "image-preview-target": "input",
        action: "change->image-preview#preview"
      } %>

            <img src="<%= f.object.question_picurl.attached? ? url_for(f.object.question_picurl) : '#' %>" alt="Image Preview" class="mt-2 aspect-[16/9]  object-contain bg-transparent rounded-xl shadow-lg border border-gray-400 <%= f.object.question_picurl.attached? ? '' : 'hidden' %>" data-image-preview-target="preview" />
        </div>


        <p>
            <%= f.label :answer1, class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.text_field :answer1, class: "w-full px-2 h-10 border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <p>
            <%= f.label :answer2, class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.text_field :answer2, class: "w-full px-2 h-10 border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <p>
            <%= f.label :answer3, class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.text_field :answer3, class: "w-full px-2 h-10 border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <p>
            <%= f.label :answer4, class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.text_field :answer4, class: "w-full px-2 h-10 border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <p>
            <%= f.label :correct_answer, "Correct Answer (1 – 4)", class: "text-sm cursor-pointer font-medium" %><br>
            <%= f.number_field :correct_answer, in: 1..4, class: "w-full px-2 h-10 border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
        </p>

        <div class="flex justify-end mt-2">
            <%= link_to_remove_association "Remove Question", f, class: "remove-question flex justify-end h-10 w-fit px-4 rounded-xl bg-red-400 flex items-center justify-center text-white" %>
        </div>
    </div>
</div>

app/views/categories/answer.html.erb
<h2>Answer Questions for <%= @category.category_name %></h2>

<%= form_with url: submit_answers_category_path(@category), method: :post do %>
  <% @questions.each do |question| %>
    <div class="mb-6 border p-4 rounded-lg shadow">
      <p class="font-semibold"><%= question.content %></p>

      <% [:answer1, :answer2, :answer3, :answer4].each do |answer_option| %>
        <div>
          <%= radio_button_tag "user_answers[#{question.id}][selected_answer]", question.send(answer_option), false, id: "#{question.id}_#{answer_option}" %>
          <%= label_tag "#{question.id}_#{answer_option}", question.send(answer_option) %>
        </div>
      <% end %>
    </div>
  <% end %>

  <%= submit_tag "Submit Answers", class: "px-4 py-2 bg-blue-500 text-white rounded" %>
<% end %>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/edit_questions.html.erb
<div class="border border-gray-400 rounded-xl p-4 mt-4 mb-4 md:max-w-3xl mx-auto">
<%= form_with model: @category, url: update_questions_category_path(@category), local: true, html: { multipart: true } do |f| %>
<div>
    <h1 class="text-center text-2xl font-semibold"> Edit Quiz? </h1>
    <div class="flex flex-col gap-2">
    <p>
        <%= f.label :category_name,class:"text-sm font-medium" %><br>
        <%= f.text_field :category_name , class: "w-full px-2 h-10 border focus:border text-sm focus:border-blue-400 border-gray-400 rounded-xl" %>
    </p>

    <p>
        <%= f.label :category_description ,class:"text-sm font-medium "%><br>
        <%= f.text_area :category_description, class: "w-full px-2 h-10 min-h-[5rem] border focus:border text-sm focus:border-blue-400 border-gray-400 pt-1 rounded-xl" %>
    </p>

    <p class="w-fit ">
        <%= f.label :Category_Picture,class:"text-sm cursor-pointer font-medium" %><br>
        <%= f.file_field :category_picurl, class: "mt-1 block w-fit cursor-pointer text-sm  text-gray-900 file:mr-4 file:py-2 file:px-4 file:rounded-xl  file:text-sm file:font-semibold file:border file:border-rose-400 file:text-black hover:file:bg-blue-50" %>
    </p>
    </div>
</div>

<div id="questions" class="flex flex-col space-y-4 mt-2">
    <%= f.fields_for :questions do |qf| %>
    <%= render 'question_fields', f: qf ,index: qf.index.to_i + 1%>
    <% end %>
</div>


<div class="flex items-center gap-4 mt-4">
<%= link_to_add_association ' Add Question', f, :questions,
class: "inline-block text-white bg-blue-500 px-4 py-2 rounded hover:bg-blue-600 transition rounded-xl",
data: { association_insertion_node: '#questions', association_insertion_method: :append } %>

<%= f.submit "Update Questions",class:"flex justify-end h-10 w-fit px-4 rounded-xl bg-green-400 flex items-center justify-center text-white" %>
</div>
<% end %>
</div>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>